### ISSUE TITLE
Should validate changeset 'source' is in config hierarchy

### ISSUE THREAD

**Issue by macgregor** [alechenninger/monarch#27]
You can specify a source in your changeset that is not in the hierarchy. I dont think it is trying to apply the changeset, but at the very least it is still rewriting your hieradata output in alphabetical order. 

Should probably verify that the source is declared in your hierarchy and fail loudly.

**Comment by alechenninger** [comment]
> Should probably verify that the source is declared in your hierarchy and fail loudly.

Agreed. Thank you!

**Comment by alechenninger** [comment]
Hrm can you give a more detailed outline of the scenario you experienced? Right now we're validating the target is in the hierarchy, and looking for any changes for anything in the hierarchy. No part of the process explicitly requires that all of the sources in a changeset exist in the hierarchy, only that the target exists in the hierarchy. There may or may not be changes for sources in the hierarchy which is intentional of course.

Are you trying to catch misconfigured hierarchy or misconfigured change or either?
